//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public int ID { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public string CEP { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual People People { get; set; }
    }
}
