//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
    
        public virtual DiscountTypes DiscountTypes { get; set; }
        public virtual People People { get; set; }
    }
}
