//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2___DesktopSP__FollowWS_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sessao5Entities : DbContext
    {
        public Sessao5Entities()
            : base("name=Sessao5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<Jogadores> Jogadores { get; set; }
        public DbSet<Jogos> Jogos { get; set; }
        public DbSet<Notificacoes> Notificacoes { get; set; }
        public DbSet<NotificacoesUsuarios> NotificacoesUsuarios { get; set; }
        public DbSet<Posicoes> Posicoes { get; set; }
        public DbSet<Rodadas> Rodadas { get; set; }
        public DbSet<Selecoes> Selecoes { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
