//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2___DesktopSP__FollowWS_
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacoesUsuarios
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> NotificacaoId { get; set; }
    }
}
