//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacional2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacao
    {
        public int id { get; set; }
        public System.DateTime dataHora { get; set; }
        public string notificacao1 { get; set; }
        public int idusuario { get; set; }
        public string status { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
