//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Value { get; set; }
        public byte[] Photo{ get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Attachment { get; set; }
    
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual People People { get; set; }
    }
}
