//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequencies
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Checkin { get; set; }
        public Nullable<System.TimeSpan> Checkout { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
