//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session2Entities : DbContext
    {
        public Session2Entities()
            : base("name=Session2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Benefits> Benefits { get; set; }
        public virtual DbSet<BenefitsDetails> BenefitsDetails { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<DiscountTypes> DiscountTypes { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Frequencies> Frequencies { get; set; }
        public virtual DbSet<Holydays> Holydays { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<PersonBenefits> PersonBenefits { get; set; }
        public virtual DbSet<PersonBenefitsDetails> PersonBenefitsDetails { get; set; }
        public virtual DbSet<PersonTypes> PersonTypes { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<TransportationTypes> TransportationTypes { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
    }
}
