//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBenefits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonBenefits()
        {
            this.PersonBenefitsDetails = new HashSet<PersonBenefitsDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> BenefitID { get; set; }
        public Nullable<System.DateTime> CancelationDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Occurrence { get; set; }
        public Nullable<System.DateTime> SolicitationDate { get; set; }
    
        public virtual Benefits Benefits { get; set; }
        public virtual People People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonBenefitsDetails> PersonBenefitsDetails { get; set; }
    }
}
