//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBenefitsDetails
    {
        public int ID { get; set; }
        public Nullable<int> PersonBenefitID { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> TransportTypeID { get; set; }
    
        public virtual PersonBenefits PersonBenefits { get; set; }
        public virtual TransportationTypes TransportationTypes { get; set; }
    }
}
