//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_dados
    {
        public byte ID { get; set; }
        public string Codigo_Turma { get; set; }
        public string Curso { get; set; }
        public short Ano { get; set; }
        public byte Semestre { get; set; }
    }
}
