//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Curso { get; set; }
        public Nullable<int> Periodo { get; set; }
    }
}
