//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questões
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Enunciado { get; set; }
        public string Alternativa_1 { get; set; }
        public string Alternativa_2 { get; set; }
        public string Alternativa_3 { get; set; }
        public string Alternativa_4 { get; set; }
        public Nullable<int> Gabarito { get; set; }
        public string Curso { get; set; }
        public string Disciplina { get; set; }
        public string Docente { get; set; }
    }
}
