//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int Posicao { get; set; }
        public Nullable<int> Aluno { get; set; }
        public Nullable<int> Pontuacao { get; set; }
        public Nullable<int> Vitorias { get; set; }
        public Nullable<int> Derrotas { get; set; }
        public Nullable<int> Descartes { get; set; }
        public Nullable<int> Acertos { get; set; }
        public Nullable<int> Erros { get; set; }
    }
}
