<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\020220200935.jpg" />
	  <None Remove="Images\030120201555.jpg" />
	  <None Remove="Images\070820201753.jpg" />
	  <None Remove="Images\080820201836.jpg" />
	  <None Remove="Images\090820201655.jpg" />
	  <None Remove="Images\100820201233.jpg" />
	  <None Remove="Images\101220201225.jpg" />
	  <None Remove="Images\120220201750.jpg" />
	  <None Remove="Images\151020202233.jpg" />
	  <None Remove="Images\220220200932.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Images\020220200935.jpg" />
	  <EmbeddedResource Include="Images\030120201555.jpg" />
	  <EmbeddedResource Include="Images\070820201753.jpg" />
	  <EmbeddedResource Include="Images\080820201836.jpg" />
	  <EmbeddedResource Include="Images\090820201655.jpg" />
	  <EmbeddedResource Include="Images\100820201233.jpg" />
	  <EmbeddedResource Include="Images\101220201225.jpg" />
	  <EmbeddedResource Include="Images\120220201750.jpg" />
	  <EmbeddedResource Include="Images\151020202233.jpg" />
	  <EmbeddedResource Include="Images\220220200932.jpg" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Xamarin.Forms" Version="5.0.0.2196" />
		<PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Newtonsoft.Json">
			<HintPath>..\..\APIMobileMG\bin\Newtonsoft.Json.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="CadastroPage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="LoginPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="RelatosDetail.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="RelatosPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="StartingPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="StartingPageDetail.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="StartingPageFlyout.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Fonts\" />
	</ItemGroup>
</Project>