//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nacional2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competicao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competicao()
        {
            this.Jogos = new HashSet<Jogos>();
        }
    
        public int IdCompeticao { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Local { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogos> Jogos { get; set; }
    }
}
